# Generated by Django 4.2.5 on 2023-12-02 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_wallpaper'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallpaper',
        ),
    ]
