# Generated by Django 4.2.5 on 2023-12-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_wallpaper_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='categories',
            field=models.ManyToManyField(to='myapp.category'),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='status',
            field=models.BooleanField(default=False, help_text='0-show, 1-hidden'),
        ),
    ]
