# Generated by Django 4.2.7 on 2023-12-11 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_favourite_wp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite_wp',
            name='wallpaper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='myapp.wallpaper'),
        ),
    ]
