# Generated by Django 4.2.5 on 2023-12-20 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_downloadhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallpaper',
            name='price',
        ),
    ]
